name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ssh.tallyo.us
          username: gh-svc-account
          key: ${{ secrets.GH_SVC_ACCOUNT }}
          proxy_host: ssh.tallyo.us
          proxy_port: 443
          proxy_key: ${{ secrets.GH_SVC_ACCOUNT }}
          script: |
            cd ~/projects/tidbit-backend
            git pull origin main
            ./deploy.sh